# Generated by Django 5.2.6 on 2025-10-10 11:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_payment_status_alter_product_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='client_token',
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
