# Generated by Django 5.2.6 on 2025-11-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_paystack_ref_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paystack_access_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
