# Generated by Django 5.2.6 on 2025-11-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_paystack_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Preferred delivery date', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(blank=True, help_text='Preferred delivery time', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='secret_message',
            field=models.TextField(blank=True, help_text='Private message from customer', null=True),
        ),
    ]
