# Generated by Django 5.2.6 on 2025-12-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_delivery_date_order_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available'], name='store_produ_is_avai_7e0c5a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['collection'], name='store_produ_collect_d26005_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='store_produ_price_2d55a6_idx'),
        ),
    ]
