# Generated by Django 5.2.6 on 2025-12-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customization_price_at_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='with_customization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='customization_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='is_customizable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_customizable'], name='store_produ_is_cust_172ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['customization_price'], name='store_produ_customi_3ca374_idx'),
        ),
    ]
