# Generated by Django 5.2.6 on 2025-12-22 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_product_available_sizes_productsize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='stock_quantity',
        ),
    ]
