# Generated by Django 5.2.6 on 2025-12-23 07:55

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_productsize_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='', validators=[store.validators.validate_file_size]),
        ),
    ]
