# Generated by Django 5.2.6 on 2025-12-23 07:59

import cloudinary.models
import store.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[store.validators.validate_file_size], verbose_name='image'),
        ),
    ]
